services:
  # change "user" . for Ex: tuananhtd
  # Redis
  redis:
    image: redis
    container_name: user_redis
    restart: unless-stopped
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
      - ./redis-logs:/logs/
    ports:
      - PORT_REDIS:10209
    networks:
      - user_mlnet

  # Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: user_rabbitmq
    ports:
      - PORT_RABBITMQ:10202
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    networks:
      - user_mlnet

networks:
  user_mlnet:


volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-logs:
  mydata:
    # celery-logs:
    # api-logs:
