services:
  # change "user" . for Ex: tuananhtd
  # Redis
  redis:
    image: redis
    container_name: khaihd_redis
    restart: unless-stopped
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
      - ./redis-logs:/logs/
    ports:
      - 10201:6379
    networks:
      - khaihd_mlnet

  # Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: khaihd_rabbitmq
    ports:
      - 10202:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    networks:
      - khaihd_mlnet

networks:
  khaihd_mlnet:


volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-logs:
  mydata:
    # celery-logs:
    # api-logs: